#!/bin/sh

# Get the volume via pulsemixer

[ $(pulsemixer --get-mute) = 1 ] && echo "<icon=volume/mute.xpm/>" && exit

vol="$(pulsemixer --get-volume | awk '{ print ($1+$2)/2 }')"
if [ "$vol" -gt "70" ]; then
	icon="volume/high.xpm"
elif [ "$vol" -lt "30" ]; then
	icon="volume/low.xpm"
else
	icon="volume/medium.xpm"
fi

echo "<icon=$icon/><fn=2>$vol%</fn>"

exit 0
